// Bridge functions (all domains)
export {
  SDK_VERSION,
  isNative,
  getSelfLocation,
  getMapCenter,
  addMarker,
  updateMarker,
  removeMarker,
  panTo,
  getPreference,
  setPreference,
  removePreference,
  getManagedUids,
  getMapItemsSnapshot,
  getMapItem,
  getMapGroups,
  getPluginMarkers,
  startMapItemStream,
  stopMapItemStream,
  setItemMeta,
  setItemMetaDouble,
  setItemMetaBool,
  getItemMeta,
  setMarkerIcon,
  createMapGroup,
  removeMapGroup,
  setGroupVisible,
  addShape,
  addCircle,
  addEllipse,
  addRectangle,
  updateShape,
  removeShape,
  getManagedShapeUids,
  getPluginShapes,
  addRoute,
  updateRoute,
  addWaypoint,
  removeWaypoint,
  removeRoute,
  startNavigation,
  stopNavigation,
  getManagedRouteUids,
  getPluginRoutes,
  getNavigationState,
  onNavigationStateChanged,
  sendCot,
  sendCotToContacts,
  registerAction,
  unregisterAction,
  sendBroadcast,
  toMGRS,
  toUTM,
  fromMGRS,
  fromUTM,
  getCoordinateFormat,
  formatCoordinate,
  distanceTo,
  type CoordinateFormat,
  setDropdownSize,
  getDropdownSize,
  setNavVisible,
  getNavVisible,
  type DropdownDimension,
  sendMessage,
  openConversation,
  getChatHistory,
  getConversations,
  createGeofence,
  removeGeofence,
  dismissGeofenceAlert,
} from './bridge';

// Stores
export {
  mapItemStore,
  matchesFilter,
  cotStore,
  contactStore,
  matchesContactFilter,
  chatStore,
} from './stores';

// Event system
export { on, off } from './events';

// React hooks
export {
  useSelfLocation,
  useMapEvent,
  useAtakEvent,
  useMapItems,
  useMapItem,
  useMapGroups,
  usePluginMarkers,
  useCoordinateFormat,
  useIntent,
  useIntentCallback,
  useCotStream,
  useCotEvent,
  useDropdownVisible,
  useDropdownSize,
  useNavVisible,
  usePreference,
  useMenuAction,
  useNavigationState,
  useContacts,
  useContact,
  useChat,
  useGeofenceAlerts,
} from './hooks';

// Types
export type {
  GeoPoint,
  SelfLocation,
  MarkerOptions,
  MarkerUpdateOptions,
  MapClickEvent,
  ItemSelectedEvent,
  MapItemData,
  MapItemFilter,
  MapGroupData,
  MapItemsChangedEvent,
  AtakEventName,
  AtakEventMap,
  IntentData,
  CotEventData,
  CotDispatchTarget,
  MarkerIconOptions,
  MenuActionEvent,
  ShapeOptions,
  CircleOptions,
  EllipseOptions,
  RectangleOptions,
  ShapeUpdateOptions,
  RouteOptions,
  RouteUpdateOptions,
  WaypointOptions,
  NavigationState,
  RouteMethod,
  RouteDirection,
  ContactData,
  ContactFilter,
  ChatMessageData,
  ConversationInfo,
  GeofenceAlertData,
  GeofenceOptions,
} from './types';
